[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "SNFit"
version = "0.0.1"

dependencies = [
    "numpy",
    "dash",
    "plotly",
    "matplotlib",
    "pandas",
]